---
title: "Week5"
author: "Jonathan Franks"
date: "February 12, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Week 5


###Question 1

####Part a
```{r}
df <- read.table(file="yob2016.txt", header= FALSE, sep=";")
colnames(df) = c("Name", "Sex", "N")
```

####Part b
```{r}
str(df)
summary(df)
```

####Part c
```{r}
grep("*yyy", df$Name)
y2016 <-df[-212,]
```

####Part d
```{r}
y2016 <-df[-212,]
```

###Question 2

####Part a
```{r}
y2015 <- read.table(file="yob2015.txt", header= FALSE, sep=",")
colnames(y2015) = c("Name", "Sex", "N")
```

####Part b
```{r}
tail(y2015, 10)
```
The last ten rows each contain only 5 kids named that for the year and they are all male.

####Part c
```{r}
Final <- merge(y2015, y2016, by=c("Name", "Sex"))
```


###Question 3

####Part a
```{r}
Final$Total <- rowSums(Final[,c("N.x","N.y")])
```
####Part b
```{r}
Final <- Final[order(-Final$Total),]
head(Final,10)
```
####Part c
```{r}
Final <- Final[Final$Sex=="F",]
head(Final,10)
```
####Part d
```{r}
write.table(Final[0:10,c("Name","Total")],"Names.csv")
```


GITHUB:https://github.com/jfranks9/SMU-MSDS/tree/master/6306/Week5