---
title: "Assignment 11"
author: "Jonathan Franks"
date: "April 07, 2018"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE, warning=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#Load Libraries
library(fpp2)
library(xts)
library(dygraphs)
```

###Question 1: Warm up
```{r}
#pulling dax from data - PART A
Dax <- EuStockMarkets[,1]
```


```{r}
#Plot - PART B
plot.ts(Dax, col="blue")
title("Dax Closing Prices 1991-1998")
abline(v=1997.000, col="red")
```

```{r}
#Decompostion - Part C
DaxC <- decompose(Dax)
plot(DaxC, col="blue")
abline(v=1997.00, col="red")

```

###Question 2: Temperature Data
```{r}
#Part A look at dataset 'maxtemp'
#help(maxtemp)
autoplot(maxtemp)
head(maxtemp)
```

```{r}
#Part B - Subset data to 1990-present
tempdat <- window(maxtemp, start=1990)
autoplot(tempdat)

```

```{r, warning=FALSE}
#Part C - SES Forecasting
fit1 <- ses(tempdat, initial="optimal", h=4)
plot(fit1, plot.conf=FALSE, ylab="Yearly MaxTemp in Celsius", col="red",
  xlab="Year", main="", fcol="white", type="o")
lines(fitted(fit1), col="blue", type="o")
lines(fit1$mean, col="blue", type="o")
legend("topleft",lty=1, col=c("red","blue"), 
  c("data", "SES"),pch=1)
#Get AICc
summary(fit1)

```

```{r, warning=FALSE}
#Part D - Holt Forecasting
fit2 <- holt(tempdat, damped=TRUE, initial="optimal", h=4)
plot(fit2, plot.conf=FALSE, ylab="Yearly MaxTemp in Celsius", col="red",
  xlab="Year", main="", fcol="white", type="o")
lines(fitted(fit1), col="blue", type="o")
lines(fit1$mean, col="blue", type="o")
legend("topleft",lty=1, col=c("red","blue"), 
  c("data", "Holt"),pch=1)
#Get AICc
summary(fit2)

```
####AICc Discussion
The SES AICc value is 141.5302 and the Holt AICc value is 144.5819. 
Holt's AICc value being greater than SES indicates a worse fit in the model.
Therefore, the SES model is better because of the lower AICc.

###Question 3
```{r}
#Part A - load data
Olli <- read.csv("Unit11TimeSeries_Ollivander.csv", header = FALSE)
Greg <- read.csv("Unit11TimeSeries_Gregorovitch.csv", header = FALSE)
Names <- c("Date", "WandSales")
#Part B - Set date to date class
Olli$V1 <- as.Date(Olli$V1, "%d/%m/%Y")
colnames(Olli) <- Names
Greg$V1 <- as.Date(Greg$V1, "%d/%m/%Y")
colnames(Greg) <- Names
head(Olli)
head(Greg)

```

```{r}
#Part C - xts objects
Oxts <- xts(Olli, order.by=Olli$Date)
Gxts <-xts(Greg, order.by=Greg$Date)
#head(Oxts)
#head(Gxts)

```

```{r}
#Part D - Bind and Graph
xts1 <- merge.xts(Gxts,Oxts)
#Clean up new dataset
xts2 <- xts1[,-c(1,3)]
colnames(xts2) <- c("Gregorovitch","Ollivander")
head(xts2)
#Make the graph stacked with options
dygraph(xts2) %>% 
  dyOptions(stackedGraph = FALSE,includeZero = TRUE) %>%
  dySeries("Ollivander", label = "Ollivander", color = "blue", fillGraph=TRUE) %>%
  dySeries("Gregorovitch", label = "Gregorovitch", color = "#0c7501", fillGraph=TRUE) %>%
  dyAxis('x', label="Year") %>%
  dyAxis('y', label="Number of Wands Sold") %>%
    dyShading(from="1995-1-1", to= "1999-1-1", axis = "x", color = "#ef9999") %>%
  dyHighlight(hideOnMouseOut = FALSE) %>%
   dyRangeSelector(height = 20)
```






